version: "3"
services:

  filebeat:
    image: "docker.elastic.co/beats/filebeat:7.2.0"
    container_name: filebeat_loggly
    user: root
    volumes:
      - /home/gonzalo/Documents/2.-Proyectos/micro_elk_server/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    depends_on:
      - logstash

  logstash:
    build: .
    container_name: logstash_loggly
    command: logstash -f /logstash.conf
    environment:
      - TOKEN=${TOKEN}
    volumes:
      - /home/gonzalo/Documents/2.-Proyectos/micro_elk_server/logstash.conf:/logstash.conf
      - /home/gonzalo/Documents/2.-Proyectos/micro_elk_server/logstash.yml:/usr/share/logstash/config/logstash.yml
    restart: always
